### ISSUE TITLE
S3 Metadata Archive Format

### ISSUE THREAD

**Issue by daniel-chou** [allenai/s2-gorc#5]
The metadata file at the S3 path (`s3://ai2-s2-gorc-release/20190928/metadata.tar.gz`) appears to be in bzip2 format. Would you consider renaming the file? Perhaps `metadata.tar.bz2` would be a possibility?

**Comment by kyleclo** [comment]
Hey @daniel-chou sorry for the delay.

While looking into the metadata issue, we also decided to modify the tarball situation.  Instead, we've sharded the metadata file into multiple files, one per batch of papers.

They can be found at `ai2-s2-gorc-release/20190928/metadata/` labeled `0.tsv`, `1.tsv`, ..., to `10000.tsv`.

Hopefully this makes things easier!

**Comment by daniel-chou** [comment]
@kyleclo Thanks for sharding the metadata file into multiple TSV files! This works well for me. 👍 

Just to confirm the `.tsv` files range from 0 to 9998; neither `9999.tsv` nor `10000.tsv` exists. Is this correct?

**Comment by kyleclo** [comment]
Ah, nice catch!  Looks like forgot to copy `9999.tsv` over. It's added now.  There is no `10000.tsv`.   Thanks!

**Comment by daniel-chou** [comment]
Great! I downloaded `9999.tsv` just now. Thank you for resolving this issue. 👍
